### ISSUE TITLE
apply_along_axis incredibly slow?

### ISSUE THREAD

**Issue by jhallard** [thobbs/color-clustering#1]
Thank you for writing this! While testing it, I noticed that we spend an incredible amount of time doing this line

```python
    flat_img = np.apply_along_axis(lambda a: (a[0] / 255.0, a[1] / 255.0, a[2] / 255.0), 2, flat_img)
```

Some timing results:

Run over this image: 
![image](https://user-images.githubusercontent.com/7551586/34858219-dda8b29c-f703-11e7-9f2b-06fb4e506339.png)

with this command:
```bash
$ python color_clustering.py /tmp/croppings_925808731/image_2122787308.jpg -k 4 -r 10 -f /tmp/image.jpg
```

Gives these timing results

```
time to flatten asarray: 0.01 seconds
time to apply long axis: 10.42 seconds
time to rgb to hsv: 0.10 seconds
time to reshape: 0.00 seconds
time to get_stdev: 0.02 seconds
time to whiten: 0.02 seconds
time to kmeans: 1.87 seconds
time to unwhiten: 0.00 seconds
time to match counts: 8.08 seconds
```

10 seconds to run the code along the axis to normalize, that's the vast majority of the runtime. I think there's room for a major speed up there.

**Comment by jhallard** [comment]
LOL

all you have to do is change

```
    flat_img = np.apply_along_axis(lambda a: (a[0] / 255.0, a[1] / 255.0, a[2] / 255.0), 2, flat_img)
```

to 

```
flat_img = flat_img / 255.0
```

for a speed up from 10.42 seconds to 0.00 seconds

```
time to flatten asarray: 0.01 seconds
time to apply long axis: 0.00 seconds
time to rgb to hsv: 0.09 seconds
time to reshape: 0.00 seconds
time to get_stdev: 0.01 seconds
time to whiten: 0.02 seconds
time to kmeans: 1.94 seconds
time to unwhiten: 0.00 seconds
time to match counts: 8.49 seconds
```

**Comment by thobbs** [comment]
I just noticed this issue (a few years late, hah!). Fixed, thanks for taking the time to look into that!
